### ISSUE TITLE
So, this version is only for single retrieval for PIR?

### ISSUE THREAD

**Issue by InnovationFlash** [Microsoft/SealPIR#13]
I read related paper, and found this is method were post for multi-queries.

But I found the Demo only implement the single-query, what i missed?.....

**Comment by sga001** [comment]
We implemented probabilistic batch codes (multi-query PIR) in a different code base. See here: https://github.com/sga001/mpir

**Comment by lidh15** [comment]
> We implemented probabilistic batch codes (multi-query PIR) in a different code base. See here: https://github.com/sga001/mpir

But this repo is no longer maintained since three years ago, I wonder if there is something still alive.

**Comment by sga001** [comment]
No, I have not updated that project since.
