### ISSUE TITLE
Does sealpir support multi-core computing？

### ISSUE THREAD

**Issue by qwerfdg** [Microsoft/SealPIR#26]
I found the following information in your paper “We run the PIR servers on H16 instances (16-core 3.6 GHz Intel Xeon E5-2667 and 112 GB RAM), and clients on F16s instances (16-core, 2.4 GHz Intel Xeon E5-2673 and 32 GB RAM), all running Ubuntu 16.04.”. It seems that sealpir support multi-core parallel computing. But when I run main.cpp, I only use one cpu core.

**Comment by sga001** [comment]
We only use 1 CPU in all of the experiments in the paper.
