### ISSUE TITLE
How does SealPIR support Keyword PIR?

### ISSUE THREAD

**Issue by HaoXuan40404** [Microsoft/SealPIR#27]
I found that many libraries that depend on SEAL PIR support Keyword PIR. However, when I read the paper "PIR with compressed queries and amortized query processing", I only found index PIR mentioned.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/34049754/223313626-f476efd1-e17e-46e2-aba1-39e50c686100.png">
However, the paper also states that SEAL PIR can support the keyword model. This is achieved by encoding the keywords as bit vectors and representing them as polynomials. The client then encrypts these polynomials and sends them to the server, which evaluates them using homomorphic operations. This allows the server to retrieve the matching documents without learning the keywords.

I wanna which paper or any other research papers that specifically focus on implementing keyword PIR using SEAL PIR, where could I found it

**Comment by sga001** [comment]
SealPIR can be used as a *black box* with a PIR-by-keywords scheme. But this is not implemented in the SealPIR codebase. You'll need to implement the PIR by keywords scheme yourself. They are fairly straightforward. The most trivial example is to just send the mapping between keywords and indices. Another example is to use the binary search approach described in [32] where you use PIR many times on databases of varying sizes.

**Comment by ivila** [comment]
@HaoXuan40404 Maybe you can try the Labeled PSI provided by (https://github.com/microsoft/APSI.git), by using keyword as Item, and concating rows with same keyword together as one Label.
