### ISSUE TITLE
PBC

### ISSUE THREAD

**Issue by Yohjishong** [Microsoft/SealPIR#32]
Where is PBC used

**Comment by sga001** [comment]
It is not in this repository. This repository only contains SealPIR. 

See https://github.com/sga001/mpir for the code that uses PBC.

**Comment by Yohjishong** [comment]
Thanks, and is there a C++ version of mpir?

**Comment by Yohjishong** [comment]
and I can't understand how to merge cuckoo hash and batch node into PBC

**Comment by sga001** [comment]
No, there is no C++ version. Only rust. 

This code has the algorithm: https://github.com/sga001/mpir/blob/master/src/pbc/cuckoo.rs

**Comment by Yohjishong** [comment]
Is the mpir can run without the code in the Sealpir

**Comment by sga001** [comment]
The mpir repository has a Rust wrapper for SealPIR. It uses a particular version of SealPIR (C++) underneath.
