### ISSUE TITLE
About Ctest

### ISSUE THREAD

**Issue by whale-withme** [Microsoft/SealPIR#37]
hello, i'm on ubuntu 22.04 and try`ctest .` under SealPIR, but found some exceptions.
```
Test project /home/whale/lab/SealPIR
    Start 1: coefficient_conversion_test
1/6 Test #1: coefficient_conversion_test ......   Passed    0.01 sec
    Start 2: expand_test
2/6 Test #2: expand_test ......................Child aborted***Exception:   0.83 sec
    Start 3: query_test
3/6 Test #3: query_test .......................Child aborted***Exception:   1.29 sec
    Start 4: simple_query_test
```
my issues are:
1.  why appear `Child aborted`? is this my configuration problem?
2. test 4 and latter are slow, i waited for about 5 minutes and no response. Is this normal? I read another question that random seed may cause it, but it seems toooo long for only one test?
```[tasklist]
### Tasks
```

**Comment by Saikrishna-Achalla** [comment]
I have the same issue but test 3 is extremely slow in my case (10+ mins with no response)

**Comment by whale-withme** [comment]
@Saikrishna-Achalla Because it use random seeds to generate database in order to simulate PIR and it is very time consuming. I replace related code into pre-processed batabase and it works.

**Comment by sga001** [comment]
See #23 .

Unfortunately because this repo is under Microsoft and I no longer work there I cannot merge this directly. I'll ask Kim.

**Comment by sga001** [comment]
We have merged the changes.

**Comment by Saikrishna-Achalla** [comment]
@sga001 Thanks. Time decreased significantly!
