### ISSUE TITLE
What is CIPHER_SIZE?

### ISSUE THREAD

**Issue by ReverseControl** [Microsoft/SealPIR#8]
In the file main.cpp there is this comment:

```
    //To marshall query to send over the network, you can use serialize/deserialize:
    //std::string query_ser = serialize_query(query);
    //PirQuery query2 = deserialize_query(d, 1, query_ser, CIPHER_SIZE);
```

What is CIPHER_SIZE? The number of coefficients of a ciphertext? The number of bytes? Could you please define it? A macro or function would be fine.

Also, what is the meaning of the 1? A little documentation would be helpful.

**Comment by sga001** [comment]
Macro is defined in pir.hpp (https://github.com/microsoft/SealPIR/blob/master/pir.hpp#L10).

deserialize_query is also defined in pir.hpp:

`PirQuery deserialize_query(std::uint32_t d, uint32_t count, std::string s, std::uint32_t len_ciphertext);`

If my memory serves me right, d is the number of dimensions, count is the number of ciphertexts needed to encode the index in each dimension, s is the serialized query, and len_ciphertext is the size of the ciphertext in bytes.

**Comment by ReverseControl** [comment]
I have:

```
N = 4096
q = CoeffModulus::BFVDefault( N )  (SEAL v3.5.8)
t = 257

Ciphertext cp_data;   <-- I encrypt some data, and it is stored here.

cp.int_array().size() = 16384;   <- I expected this to be twice this size.
string data_serialized =   serialize_data( cp );
data_serialized.size() = 91194;
```

So, should CIPHER_SIZE be 16384?
